#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def agent_datacore_arguments(params, hostname, ipaddress):
    args = quote_shell_string(ipaddress)
    args += " " + quote_shell_string(params["username"])
    args += " " + quote_shell_string(params["password"])

    if "port" in params:
        args += " --port " + str(params["port"])

    if "server" in params:
        args += " --server " + str(params["server"])

    if "protocol" in params:
        if str(params["protocol"]) == '1':
            args += " --protocol https"
        else:
            args += " --protocol http"

    if "ssl" in params:
        args += " --ignoressl"

    return args

special_agent_info['datacore'] = agent_datacore_arguments